version: '3.7'

services:
  PostgresDB:
    image: postgres
    container_name: Postgres
    volumes:
      - db-data:/data/postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - PGDATA=/data/postgres
    restart: unless-stopped

  PG_Admin:
    image: dpage/pgadmin4
    container_name: PG-Admin
    volumes:
      - pgadmin-data:/data/pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    restart: unless-stopped

  UserService:
    image: dexam_user_service
    container_name: UserService
    volumes:
      - user-service-data:/data/user_service
    ports:
      - "8080:8080"
    environment:
      - DB_HOSTNAME=PostgresDB
      - POSTGRES_PORT=5432
      - POSTGRES_DBNAME=postgres
      - POSTGRES_USERNAME=admin
      - POSTGRES_PASS=admin
      - VERIFICATION_MAIL_USERNAME=eyadyoussef69@gmail.com
      - VERIFICATION_MAIL_PASSWORD=ifobbplpqanlsqjx
    restart: unless-stopped

volumes:
  db-data:
  pgadmin-data:
  user-service-data: